spring:
  application:
    name: searching-service
  profiles:
    active: ou

server:
  port: 9999
  tomcat:
    max-threads: 4

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/
    
constants:
  housing-url: http://housing.icho.osaka-u.ac.jp/dormitory/search

