spring:
  application:
    name: searching-service
  ###邮件
  mail:
    host: smtp.qq.com
    port: 465
    username: 543296676@qq.com
    password: bpzdtgqupkdjbfch
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            auth: true

server:
  port: 9999
  tomcat:
    max-threads: 4

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka/

#邮件发送者
mail:
  fromMail:
    addr: ${spring.mail.username}
    
constants:
  housing-url: http://housing.icho.osaka-u.ac.jp/dormitory/search

